name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: SiliconLabs/close-pull-request-target@v2.2
      with:
        comment: "This repo does not accept PRs. All bug reports or questions should be handled via issues. Please refer to the readme for instructions on reporting issues. If you have a general question for Silicon Labs, visit www.silabs.com/support for assistance."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
